package langdetect

var langEnglish = map[Language]string{
Aa:"Afar",
Ab:"Abkhaz",
Ae:"Avestan",
Af:"Afrikaans",
Ak:"Akan",
Am:"Amharic",
An:"Aragonese",
Ar:"Arabic",
As:"Assamese",
Av:"Avar",
Ay:"Aymara",
Az:"Azerbaijani",
Ba:"Bashkir",
Be:"Belarusian",
Bg:"Bulgarian",
Bh:"Bihari",
Bi:"Bislama",
Bm:"Bambara",
Bn:"Bengali",
Bo:"Tibetan",
Br:"Breton",
Bs:"Bosnian",
Ca:"Catalan, Valencian",
Ce:"Chechen",
Ch:"Chamorro",
Co:"Corsican",
Cr:"Cree",
Cs:"Czech",
Cu:"Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic",
Cv:"Chuvash",
Cy:"Welsh",
Da:"Danish",
De:"German",
Dv:"Dhivehi, Dhivehi, Maldivian",
Dz:"Dzongkha",
Ee:"Ewe",
El:"Modern Greek",
En:"English",
Eo:"Esperanto",
Es:"Spanish, Castilian",
Et:"Estonian",
Eu:"Basque",
Fa:"Persian",
Ff:"Fula",
Fi:"Finnish",
Fj:"Fijian",
Fo:"Faroese",
Fr:"French",
Fy:"West Frisian",
Ga:"Irish",
Gd:"Gaelic, Scottish Gaelic",
Gl:"Galician",
Gn:"Guaraní",
Gu:"Gujarati",
Gv:"Manx",
Ha:"Hausa",
He:"Modern Hebrew",
Hi:"Hindi",
Ho:"Hiri Motu",
Hr:"Croatian",
Ht:"Haitian Creole, Haitian Creole",
Hu:"Hungarian",
Hy:"Armenian",
Hz:"Herero",
Ia:"Interlingua (International Auxiliary Language Association)",
Id:"Indonesian",
Ie:"Interlingue, Occidental",
Ig:"Igbo",
Ii:"Yi, Nuosu",
Ik:"Inupiaq",
Io:"Ido",
Is:"Icelandic",
It:"Italian",
Iu:"Inuktitut",
Ja:"Japanese",
Jv:"Javanese",
Ka:"Georgian",
Kg:"Kongo",
Ki:"Gikuyu, Kikuyu",
Kj:"Kwanyama, Kuanyama",
Kk:"Kazakh",
Kl:"Kalaallisut, Greenlandic",
Km:"Central Khmer",
Kn:"Kannada",
Ko:"Korean",
Kr:"Kanuri",
Ks:"Kashmiri",
Ku:"Kurdish",
Kv:"Komi",
Kw:"Cornish",
Ky:"Kyrgyz, Kirgiz",
La:"Latin",
Lb:"Luxembourgish, Letzeburgesch",
Lg:"Luganda",
Li:"Limburgish, Limburgan, Limburger",
Ln:"Lingala",
Lo:"Lao",
Lt:"Lithuanian",
Lu:"Luba-Katanga",
Lv:"Latvian",
Mg:"Malagasy",
Mh:"Marshallese",
Mi:"Māori",
Mk:"Macedonian",
Ml:"Malayalam",
Mn:"Mongolian",
Mr:"Marathi",
Ms:"Malay",
Mt:"Maltese",
My:"Burmese",
Na:"Nauruan",
Nb:"Norwegian Bokmål",
Nd:"Northern Ndebele",
Ne:"Nepali",
Ng:"Ndonga",
Nl:"Dutch, Flemish",
Nn:"Norwegian Nynorsk",
No:"Norwegian",
Nr:"Southern Ndebele",
Nv:"Navajo, Navaho",
Ny:"Chichewa, Chewa, Nyanja",
Oc:"Occitan (after 1500)",
Oj:"Anishinaabe",
Om:"Oromo",
Or:"Oriya",
Os:"Ossetic, Ossetian",
Pa:"Punjabi, Panjabi",
Pi:"Pali, Pāli",
Pl:"Polish",
Ps:"Pashto, Pushto",
Pt:"Portuguese",
Qu:"Quechua",
Rm:"Romansh",
Rn:"Kirundi",
Ro:"Romanian, Moldavian, Moldovan",
Ru:"Russian",
Rw:"Kinyarwanda",
Sa:"Sanskrit",
Sc:"Sardinian",
Sd:"Sindhi",
Se:"Northern Sami",
Sg:"Sango",
Si:"Sinhala, Sinhalese",
Sk:"Slovak",
Sl:"Slovene",
Sm:"Samoan",
Sn:"Shona",
So:"Somali",
Sq:"Albanian",
Sr:"Serbian",
Ss:"Swati",
St:"Sotho",
Su:"Sundanese",
Sv:"Swedish",
Sw:"Swahili",
Ta:"Tamil",
Te:"Telugu",
Tg:"Tajik",
Th:"Thai",
Ti:"Tigrinya",
Tk:"Turkmen",
Tl:"Tagalog",
Tn:"Tswana",
To:"Tongan (Tonga Islands)",
Tr:"Turkish",
Ts:"Tsonga",
Tt:"Tatar",
Tw:"Twi",
Ty:"Tahitian",
Ug:"Uyghur, Uyghur",
Uk:"Ukrainian",
Ur:"Urdu",
Uz:"Uzbek",
Ve:"Venda",
Vi:"Vietnamese",
Vo:"Volapük",
Wa:"Walloon",
Wo:"Wolof",
Xh:"Xhosa",
Yi:"Yiddish",
Yo:"Yoruba",
Za:"Zhuang, Chuang",
Zh:"Chinese",
Zu:"Zulu",
}
