package langdetect

var langNative = map[Language]string{
Aa:"Afaraf",
Ab:"Аҧсуа",
Ae:"avesta",
Af:"Afrikaans",
Ak:"Akan",
Am:"አማርኛ",
An:"aragonés",
Ar:"العربية",
As:"অসমীয়া",
Av:"авар мацӀ, магӀарул мацӀ",
Ay:"aymar aru",
Az:"azərbaycan dili",
Ba:"башҡорт теле",
Be:"Беларуская",
Bg:"български език",
Bh:"भोजपुरी",
Bi:"Bislama",
Bm:"bamanankan",
Bn:"বাংলা",
Bo:"བོད་ཡིག",
Br:"brezhoneg",
Bs:"bosanski jezik",
Ca:"Català",
Ce:"нохчийн мотт",
Ch:"Chamoru",
Co:"corsu, lingua corsa",
Cr:"ᓀᐦᐃᔭᐍᐏᐣ",
Cs:"česky, čeština",
Cu:"ѩзыкъ словѣньскъ",
Cv:"чӑваш чӗлхи",
Cy:"Cymraeg",
Da:"dansk",
De:"Deutsch",
Dv:"ދިވެހި",
Dz:"རྫོང་ཁ",
Ee:"Eʋegbe",
El:"Ελληνικά",
En:"English",
Eo:"Esperanto",
Es:"español, castellano",
Et:"eesti, eesti keel",
Eu:"euskara, euskera",
Fa:"فارسی",
Ff:"Fulfulde, Pulaar, Pular",
Fi:"suomi, suomen kieli",
Fj:"vosa Vakaviti",
Fo:"føroyskt",
Fr:"français, langue française",
Fy:"Frysk",
Ga:"Gaeilge",
Gd:"Gàidhlig",
Gl:"Galego",
Gn:"Avañe'ẽ",
Gu:"ગુજરાતી",
Gv:"Gaelg, Gailck",
Ha:"Hausa, هَوُسَ",
He:"עברית",
Hi:"हिन्दी, हिंदी",
Ho:"Hiri Motu",
Hr:"hrvatski",
Ht:"Kreyòl ayisyen",
Hu:"Magyar",
Hy:"Հայերեն",
Hz:"Otjiherero",
Ia:"Interlingua",
Id:"Bahasa Indonesia",
Ie:"Interlingue",
Ig:"Igbo",
Ii:"ꆇꉙ",
Ik:"Iñupiaq, Iñupiatun",
Io:"Ido",
Is:"Íslenska",
It:"Italiano",
Iu:"ᐃᓄᒃᑎᑐᑦ",
Ja:"日本語 (にほんご／にっぽんご)",
Jv:"basa Jawa",
Ka:"ქართული",
Kg:"KiKongo",
Ki:"Gĩkũyũ",
Kj:"Kuanyama",
Kk:"Қазақ тілі",
Kl:"kalaallisut, kalaallit oqaasii",
Km:"ភាសាខ្មែរ",
Kn:"ಕನ್ನಡ",
Ko:"한국어 (韓國語), 조선말 (朝鮮語)",
Kr:"Kanuri",
Ks:"कश्मीरी, كشميري",
Ku:"Kurdî, كوردی",
Kv:"коми кыв",
Kw:"Kernewek",
Ky:"кыргыз тили",
La:"latine, lingua latina",
Lb:"Lëtzebuergesch",
Lg:"Luganda",
Li:"Limburgs",
Ln:"Lingála",
Lo:"ພາສາລາວ",
Lt:"lietuvių kalba",
Lu:"Kiluba",
Lv:"latviešu valoda",
Mg:"Malagasy fiteny",
Mh:"Kajin M̧ajeļ",
Mi:"te reo Māori",
Mk:"македонски јазик",
Ml:"മലയാളം",
Mn:"Монгол",
Mr:"मराठी",
Ms:"bahasa Melayu, بهاس ملايو",
Mt:"Malti",
My:"ဗမာစာ",
Na:"Ekakairũ Naoero",
Nb:"Norsk bokmål",
Nd:"isiNdebele",
Ne:"नेपाली",
Ng:"Owambo",
Nl:"Nederlands, Vlaams",
Nn:"Norsk nynorsk",
No:"Norsk",
Nr:"isiNdebele",
Nv:"Diné bizaad, Dinékʼehǰí",
Ny:"chiCheŵa, chinyanja",
Oc:"Occitan",
Oj:"ᐊᓂᔑᓈᐯᒧᐎᓐ",
Om:"Afaan Oromoo",
Or:"ଓଡ଼ିଆ",
Os:"Ирон æвзаг",
Pa:"ਪੰਜਾਬੀ, پنجابی",
Pi:"पाऴि",
Pl:"polski",
Ps:"پښتو",
Pt:"Português",
Qu:"Runa Simi, Kichwa",
Rm:"rumantsch grischun",
Rn:"kiRundi",
Ro:"română",
Ru:"Русский язык",
Rw:"Ikinyarwanda",
Sa:"संस्कृतम्",
Sc:"sardu",
Sd:"सिन्धी, سنڌي، سندھی",
Se:"Davvisámegiella",
Sg:"yângâ tî sängö",
Si:"සිංහල",
Sk:"slovenčina",
Sl:"slovenščina",
Sm:"gagana fa'a Samoa",
Sn:"chiShona",
So:"Soomaaliga, af Soomaali",
Sq:"Shqip",
Sr:"српски језик",
Ss:"SiSwati",
St:"Sesotho",
Su:"Basa Sunda",
Sv:"svenska",
Sw:"Kiswahili",
Ta:"தமிழ்",
Te:"తెలుగు",
Tg:"тоҷикӣ, toğikī, تاجیکی",
Th:"ไทย",
Ti:"ትግርኛ",
Tk:"Türkmen, Түркмен",
Tl:"Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔",
Tn:"Setswana",
To:"faka Tonga",
Tr:"Türkçe",
Ts:"Xitsonga",
Tt:"татарча, tatarça, تاتارچا",
Tw:"Twi",
Ty:"Reo Mā`ohi",
Ug:"Uyƣurqə, ئۇيغۇرچە",
Uk:"українська",
Ur:"اردو",
Uz:"O'zbek, Ўзбек, أۇزبېك",
Ve:"Tshivenḓa",
Vi:"Tiếng Việt",
Vo:"Volapük",
Wa:"Walon",
Wo:"Wollof",
Xh:"isiXhosa",
Yi:"ייִדיש",
Yo:"Yorùbá",
Za:"Saɯ cueŋƅ, Saw cuengh",
Zh:"中文 (Zhōngwén), 汉语, 漢語",
Zu:"isiZulu",
}
