package langdetect

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"io/ioutil"
	"os"
	"sort"
	"strings"
	"testing"
)

type MyStruct struct {
	X []byte
}

var someXml = []byte(`<?xml version="1.0" encoding="ISO-8859-15"?><X><X>
Wikipedian kieliversiot toimivat hyvin itsenäisesti. Niillä on omat käytännöt, ja artikkelien sisällön annetaan kehittyä riippumattomasti. Artikkelien ei tarvitse olla käännöksiä toisistaan, ja eri kieliversioihin kirjoitetaankin runsaasti etenkin paikallisluonteista materiaalia, jota ei muunkielisissä Wikipedioissa vielä ole. Muutamat perusperiaatteet, kuten neutraali näkökulma, sitovat kuitenkin kaikkia versioita. Eri kieliversiot linkittävät toisiinsa sivun vasemmassa reunassa sijaitsevien interwiki-linkkien avulla. Lisäksi eri kieliversioilla on runsaasti yhteistä kuva- ja muuta mediamateriaalia.

Alexan mukaan arvioilta 60 prosenttia kaikista Wikipedian käynneistä kohdistuu englanninkieliseen versioon. Loput jakaantuvat muiden kieliversioiden kesken.

Suurin Wikipedia on englanninkielinen, jossa on yli 3 600 000 artikkelia. Saksankielisessä on yli 1 263 000, ranskankielisessä noin 1 130 000.[12] Puolankielisessä Wikipediassa on yli 800 000 artikkelia, japanin-, italian- ja hollanninkielisessä yli 500 000, portugalin- ja espanjankielisessä yli 400 000.Suomen-, Ruotsin- ja venäjänkielisessä on yli 300 000 artikkelia. kiinan- ja norjankielisessä Wikipediassa on yli 200 000 artikkelia, ja volapükin- sekä esperantonkielisessä Wikipediassa on yli 100 000 artikkelia. Yli 10 000 artikkelia on 75 Wikipediassa. Suomenkielinen Wikipedia on suhteellisen suuri verrattuna kieltä puhuvien määrään.[13] Virallisesti Wikipedia on 264 kielellä.
</X></X>`)
var someXmlInIso885915 = bytes.Replace(bytes.Replace(someXml, []byte("ä"), []byte{0xE4}, -1), []byte("ö"), []byte{0xF6}, -1)

func ExampleXml() {
	rd, cs, e := SniffXmlToUtf8(bytes.NewReader(someXmlInIso885915))
	if e != nil {
		fmt.Println(e)
		return
	}
	var v MyStruct
	d := xml.NewDecoder(rd)
	d.CharsetReader = FixXmlCharsetHandler
	e = d.Decode(&v)
	if e != nil {
		fmt.Println(e)
		return
	}
	lang := DetectLanguage(v.X, cs)
	fmt.Println("ExampleXml:", cs, lang)
	// Output: ExampleXml: ISO885915 fi
}

func TestWikipedia(t *testing.T) {
	f, e := os.Open("test_data/wikipedia")
	if e != nil {
		fmt.Println("NO test_data PRESENT EXITING")
		return
	}
	ns, e := f.Readdirnames(-1)
	if e != nil {
		panic(e)
	}
	for _, n := range ns {
		bs, e := ioutil.ReadFile("test_data/wikipedia/" + n)
		l := n[5:8]
		if l[2] == '.' {
			l = l[:2]
		}
		if e != nil {
			panic(e)
		}
		lang := DetectLanguage(bs, "")
		var alert string
		if l != lang.String() {
			alert = "WRONG ("
			if len(l) == 2 {
				alert += Language([2]byte{l[0], l[1]}).EnglishName()
			}
			alert += ")"
		}
		if lang == Unknown {
			alert = "UNKNOWN ("
			if len(l) == 2 {
				alert += Language([2]byte{l[0], l[1]}).EnglishName()
			}
			alert += ")"
		}
		fmt.Printf("%20s => %v %s %s\n", n, lang, lang.EnglishName(), alert)
	}
}

func XTestCalcTrigrams(t *testing.T) {
	f, e := os.Open("test_data/calc_trigrams")
	if e != nil {
		panic(e)
	}
	ns, e := f.Readdirnames(-1)
	if e != nil {
		panic(e)
	}
	for _, n := range ns {
		bs, e := ioutil.ReadFile("test_data/calc_trigrams/" + n)
		fmt.Println("BUILDING TRIGRAM TABLE: " + n)
		if e != nil {
			panic(e)
		}
		vs := calcLatinByteTrigram(bs)
		lim := 500
		if lim > len(vs) {
			lim = len(vs)
		}
		vs = vs[0:lim]
		x := trigramfreqs(vs)
		sort.Sort(x)
		buf := new(bytes.Buffer)
		buf.WriteString("package langdetect\n\nvar trigram_" + n + " = trigramfreqs{\n")
		for i := 0; i < lim; i++ {
			buf.WriteString(strings.Replace(fmt.Sprintf("%#v,\n", x[i]), "langdetect.", "", -1))
		}
		buf.WriteString("}\n\n")
		ioutil.WriteFile("autogenerated_trigrams_"+n+".go", buf.Bytes(), 0600)
	}
}

func BenchmarkDiff(b *testing.B) {
	for i := 0; i < b.N; i++ {
		trigram_en.Diff(trigram_fr)
	}
}

//func BenchmarkDiffOld(b *testing.B) {
//	for i := 0; i < b.N; i++ {
//		trigram_en.DiffOld(trigram_fr)
//	}
//}

func BenchmarkDetectEn(b *testing.B) {
	bs, e := ioutil.ReadFile("test_data/wikipedia/auto_en.txt")
	b.ResetTimer()
	if e != nil {
		fmt.Println("NO test_data PRESENT EXITING")
		return
	}
	for i := 0; i < b.N; i++ {
		DetectLanguage(bs, "")
	}
}

func BenchmarkDetectZh(b *testing.B) {
	bs, e := ioutil.ReadFile("test_data/wikipedia/auto_zh.txt")
	if e != nil {
		fmt.Println("NO test_data PRESENT EXITING")
		return
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		DetectLanguage(bs, "")
	}
}
